import numpy as np

from lpvkoopman.spectrum import Spectrum
from lpvkoopman.varpro import (
    basis_matrix,
    complex_basis_matrix,
    fit_boundary,
    projection_cost,
    projection_cost_grad,
    refine_spectrum,
)


RNG = np.random.default_rng(12345)
SPEC = Spectrum(pairs=[[-0.3, 2.0], [0.5, 5.0]], reals=[-1.0, 0.2])
T = np.arange(0.0, 1.5, 0.02)


def test_real_equals_complex_projection_cost():
    """The Appendix-A real reformulation must reproduce the complex cost
    exactly for real data (same column space over conjugate-closed sets)."""
    H = RNG.standard_normal((len(T), 9))
    J_real = projection_cost(SPEC, T, H)
    Vc = complex_basis_matrix(SPEC.to_complex(), T)
    Gc, *_ = np.linalg.lstsq(Vc, H.astype(complex), rcond=None)
    J_complex = float(np.sum(np.abs(H - Vc @ Gc) ** 2))
    np.testing.assert_allclose(J_real, J_complex, rtol=1e-9)


def test_analytic_gradient_matches_finite_differences():
    H = RNG.standard_normal((len(T), 5))
    theta = SPEC.pack()
    _, g = projection_cost_grad(theta, SPEC.n_pairs, T, H)
    g_fd = np.empty_like(theta)
    for k in range(len(theta)):
        e = np.zeros_like(theta)
        e[k] = 1e-6
        Jp, _ = projection_cost_grad(theta + e, SPEC.n_pairs, T, H)
        Jm, _ = projection_cost_grad(theta - e, SPEC.n_pairs, T, H)
        g_fd[k] = (Jp - Jm) / 2e-6
    np.testing.assert_allclose(g, g_fd, rtol=2e-4, atol=1e-7)


def test_fit_boundary_recovers_exact_coefficients():
    V = basis_matrix(SPEC, T)
    G_true = RNG.standard_normal((SPEC.size, 4))
    H = V @ G_true
    G, R = fit_boundary(V, H)
    np.testing.assert_allclose(G, G_true, atol=1e-8)
    assert np.linalg.norm(R) < 1e-9


def test_refine_recovers_perturbed_eigenvalues():
    """Signal generated by a known spectrum: refinement from a perturbed
    start must drive the projected cost to ~0 and recover the spectrum."""
    spec_true = Spectrum(pairs=[[-0.2, 3.0]], reals=[-0.8])
    V = basis_matrix(spec_true, T)
    H = V @ RNG.standard_normal((spec_true.size, 6))
    spec0 = Spectrum(pairs=[[-0.35, 3.4]], reals=[-1.1])
    res = refine_spectrum(spec0, T, H)
    assert res.cost < 1e-12 * np.sum(H * H)
    np.testing.assert_allclose(res.spectrum.pairs, spec_true.pairs, atol=1e-4)
    np.testing.assert_allclose(res.spectrum.reals, spec_true.reals, atol=1e-4)
